### ISSUE TITLE
Page got captured before animation completely finish

### ISSUE THREAD

**Issue by nyancodeid** [staticallyio/screenshot#2]
Sometimes the website site must run `transition-delay` on the web to make websites more alive or just to run an animation. This makes the website look dynamic so that the screenshot screenshot process is sometimes captured with too fast or even for slowing. And someone has reported to us that this behavior felt by them on their website.

Here is a side side of different, the results of screenshots and websites that should look like:

Screenshot Result            |  Browser View
:-------------------------:|:-------------------------:
![](https://user-images.githubusercontent.com/24630806/129923129-2334cdf9-7250-4428-b857-35eb77097510.png)  |  ![](https://user-images.githubusercontent.com/24630806/129923134-c339a03b-7a56-4d38-a1af-60e059bdaafc.png)

After searching for how to fix this issue finally got a clue that we need to disable this 'transition-delay' which is expected to make the animation complete and without pause.

I am working PR for this issues. Thank you.

**Comment by fransallen** [comment]
Sorry for the delay, I've merged #3 and the changes should take effect immediately.
